<div class="form-group col-lg-4" id="comodidadhotel_<?php echo $this->alreadyRendered ?>">
    <div class="panel panel-primary">
        <div class="panel-heading">
            Comodidad de hotel <?php echo $this->alreadyRendered + 1 ?> 
            <button type="button" class="close closeId" data-target="comodidadhotel_<?php echo $this->alreadyRendered ?>">&times;</button>
        </div>
        <div class="panel-body">
            <div class="form-group col-lg-15">
                <?php $fieldName = 'comodidadhotel[' . $this->alreadyRendered . '][CHOnombreEs]'; ?>
                <label for="<?php echo $fieldName ?>">Nombre (Español)*</label>
                <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Español)" data-validate="required">        
            </div>
            <div class="clearfix">

            </div> 
            <div class="form-group col-lg-15">
                <?php $fieldName = 'comodidadhotel[' . $this->alreadyRendered . '][CHOnombreEn]'; ?>
                <label for="<?php echo $fieldName ?>">Nombre (Inglés)*</label>
                <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Inglés)" data-validate="required">        
            </div>
            <div class="clearfix">

            </div> 
            <div class="form-group col-lg-15">
                <?php $fieldName = 'comodidadhotel[' . $this->alreadyRendered . '][CHOcantidad]'; ?>
                <label for="<?php echo $fieldName ?>">Cantidad  de habitaciones en el hotel</label>
                <input maxlength="<?php echo $this->maxlenghtInput ?>" type="number" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Cantidad de comodidades de este tipo" data-validate="">        
            </div>
        </div>
    </div>
</div>