<div class="form-group col-lg-4" id="comodidadhabitacion_<?php echo $this->alreadyRendered ?>">
    <div class="panel panel-primary">
        <div class="panel-heading">
            Comodidad de habitación <?php echo $this->alreadyRendered + 1 ?> 
            <button type="button" class="close closeId" data-target="comodidadhabitacion_<?php echo $this->alreadyRendered ?>">&times;</button>
        </div>
        <div class="panel-body">
            <div class="form-group col-lg-15">
                <?php $fieldName = 'comodidadhabitacion[' . $this->alreadyRendered . '][CHnombreEs]'; ?>
                <label for="<?php echo $fieldName ?>">Nombre (Español)*</label>
                <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Español)" data-validate="required">        
            </div>
            <div class="clearfix">

            </div> 
            <div class="form-group col-lg-15">
                <?php $fieldName = 'comodidadhabitacion[' . $this->alreadyRendered . '][CHnombreEn]'; ?>
                <label for="<?php echo $fieldName ?>">Nombre (Inglés)*</label>
                <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Inglés)" data-validate="required">        
            </div>
        </div>
    </div>
</div>