<div class="form-group col-lg-4" id="evento_<?php echo $this->alreadyRendered ?>">
    <div class="panel panel-primary">
        <div class="panel-heading">
            Evento <?php echo $this->alreadyRendered + 1 ?> 
            <button type="button" class="close closeId" data-target="evento_<?php echo $this->alreadyRendered ?>">&times;</button>
        </div>
        <div class="panel-body">
            <div class="form-group col-lg-15">
                <?php $fieldName = 'evento[' . $this->alreadyRendered . '][EHnombreEs]'; ?>
                <label for="<?php echo $fieldName ?>">Nombre (Español)*</label>
                <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Español)" data-validate="required">        
            </div>
            <div class="clearfix">

            </div> 
            <div class="form-group col-lg-15">
                <?php $fieldName = 'evento[' . $this->alreadyRendered . '][EHnombreEn]'; ?>
                <label for="<?php echo $fieldName ?>">Nombre (Inglés)*</label>
                <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Inglés)" data-validate="required">        
            </div>    
            <div class="clearfix">

            </div> 
            <div class="form-group col-lg-15">
                <?php $fieldName = 'evento[' . $this->alreadyRendered . '][EHdescripcionEs]'; ?>
                <label for="<?php echo $fieldName ?>">Descripción (Español)</label>
                <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big" placeholder="Descripción (Español)"></textarea>
            </div>
            <div class="clearfix">

            </div> 
            <div class="form-group col-lg-15">
                <?php $fieldName = 'evento[' . $this->alreadyRendered . '][EHdescripcionEn]'; ?>
                <label for="<?php echo $fieldName ?>">Descripción (Inglés)</label>
                <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big" placeholder="Descripción (Inglés)"></textarea>
            </div>
            <div class="clearfix">

            </div> 
            <div class="form-group col-lg-15">
                <?php $fieldName = 'evento[' . $this->alreadyRendered . '][EHdiaEs]'; ?>
                <label for="<?php echo $fieldName ?>">Día(s) *</label>
                <select id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" data-validate="required">                    
                    <?php echo $this->partial('_dias.phtml'); ?>
                </select>
            </div>
        </div>
    </div>
</div>