<div class="row">
    <div class="col-lg-4 pull-right text-center footer">
        <a href="https://www.youtube.com/user/paradisetourstahiti" target="_blank">
            <img data-rel="tooltipBottom" title="YouTube" src="<?php echo $this->baseUrl() ?>/imgs/icon-youtube.png"/>
        </a>
        <a href="https://twitter.com/paradisetours" target="_blank">
            <img data-rel="tooltipBottom" title="Twitter" src="<?php echo $this->baseUrl() ?>/imgs/icon-twitter.png"/>
        </a>
    </div>
    <div class="col-lg-4 pull-right color-white opaque" style="padding-top: 10px;">
        <?php echo date("Y")?> Paradise Tours Tahiti · Spirit of Polynesia ®
    </div>
</div>