<?php echo '
            <div class="title" > 
                Menu
             </div>
             <div class="menu_item">Usuarios</div>
             <div class="menu_item"><a href="' . $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'add')) . '">- Agregar usuario </a></div>
             <div class="menu_item"><a href="' . $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'index')) . '">- Mostrar Todos</a></div>
             <div class="menu_item"><hr></div>
             '; ?>