<div class="form-container">
    <blockquote>
        <?php if ($this->title) { ?>
        <p class="text-primary"><?php echo ($this->icon) ? '<label class="glyphicon glyphicon-' . $this->icon . '"></label> ' : ''; ?> <?php echo $this->title ?></p>
        <?php } ?>
        <?php if ($this->description) { ?>
        <small><?php echo $this->description ?></small>
        <?php } ?>
    </blockquote>
    <form id="actividadIslaForm" method="post" enctype="multipart/form-data" novalidate>
        <div class="row">
            <div class="form-group col-sm-6">
                <?php $fieldName = 'idGrupoIsla'; ?>
                <label for="<?php echo $fieldName ?>">Grupo de Islas</label>
                <br>
                <select class="form-control loadIslas" name="<?php echo $fieldName ?>" id="<?php echo $fieldName ?>">
                    <option value="">Seleccione un grupo de islas...</option>
                    <?php foreach ($this->grupoIsla as $tipo) { ?>
                    <option value="<?= $tipo[$fieldName] ?>"><?= $tipo['GInombreEs'] ?></option>                                    
                    <?php } ?>
                </select>
            </div>
            <div class="form-group col-sm-6">
                <?php $fieldName = 'idIsla'; ?>
                <label for="<?php echo $fieldName ?>">Isla *</label>
                <br>
                <select class="form-control" name="<?php echo $fieldName ?>" id="<?php echo $fieldName ?>" data-validate="<?php echo $this->validations[$fieldName] ?>">
                    <option value="">Seleccione un grupo de islas...</option>
                </select>
            </div>
            <div class="form-group col-sm-6">
            <?php $fieldName = 'IDCategoriaSitio'; ?>
                <label for="<?php echo $fieldName ?>">Categoría</label>
                <br>
                <select class="form-control" name="<?php echo $fieldName ?>" id="<?php echo $fieldName ?>" data-validate="required">
                    <?php foreach ($this->categoria as $tipo) { ?>
                    <option value="<?php echo $tipo[$fieldName] ?>"><?php echo $tipo['CSnombreEs'] ?></option>     
                    <?php } ?>
                </select>
            </div>
            <div class="form-group col-sm-6">
                <?php $fieldName = 'SInombreEs'; ?>
                <label for="<?php echo $fieldName ?>">Nombre (Español)*</label>
                <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Español)" data-validate="<?php echo $this->validations[$fieldName] ?>">        
            </div>
            <div class="form-group col-sm-6">
                <?php $fieldName = 'SInombreEn'; ?>
                <label for="<?php echo $fieldName ?>">Nombre (Inglés) *</label>
                <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Inglés)" data-validate="<?php echo $this->validations[$fieldName] ?>">        
            </div>
            <div class="form-group col-sm-6">
                <?php $fieldName = 'SIimagen'; ?>
                <label for="<?php echo $fieldName ?>">Imagen *</label>
                <input type="file" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Imagen" data-validate="<?php echo $this->validations[$fieldName] ?>">
                <p class="help-block">Archivos .jpg o .png solamente</p>
            </div>
            <div class="clearfix"></div>
            <br>
        </div>
        <div class="btn-group">
            <button type="submit" name="submit" class="btn btn-primary" data-loading-text="Validando...">Guardar</button>
            <?php /* <button type="button" data-toggle="button" class="btn btn-info" data-rel="popover" data-content="asdasdasd" title="Información">Información</button> */ ?>
            <button type="button" class="btn btn-danger" onclick='location.href = "<?php echo $this->url(array('action' => 'index')) ?>"'>Cancelar</button>
        </div>
    </form>
</div>