<?echo '
            <div class="title" > 
                Menu
             </div>
             <div class="menu_item">Capacitaciones</div>
             <div class="menu_item"><a href="' . $this->url(array('module' => 'admin', 'controller' => 'capacitacion', 'action' => 'add')) . '">- Agregar capacitacion </a></div>
             <div class="menu_item"><a href="' . $this->url(array('module' => 'admin', 'controller' => 'capacitacion', 'action' => 'index')) . '">- Mostrar Todas</a></div>
             <div class="menu_item"><hr></div>'; ?>