<div class="form-group col-lg-4" id="restobar_<?php echo $this->alreadyRendered ?>">
    <div class="panel panel-primary">
        <div class="panel-heading">
            Restaurant/Bar <?php echo $this->alreadyRendered + 1 ?> 
            <button type="button" class="close closeId" data-target="restobar_<?php echo $this->alreadyRendered ?>">&times;</button>
        </div>
        <div class="panel-body">
            <div class="form-group col-lg-15">
                <?php $fieldName = 'restobar[' . $this->alreadyRendered . '][RnombreEs]'; ?>
                <label for="<?php echo $fieldName ?>">Nombre (Español)*</label>
                <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Español)" data-validate="required">        
            </div>
            <div class="clearfix">

            </div> 
            <div class="form-group col-lg-15">
                <?php $fieldName = 'restobar[' . $this->alreadyRendered . '][RnombreEn]'; ?>
                <label for="<?php echo $fieldName ?>">Nombre (Inglés)*</label>
                <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Inglés)" data-validate="required">        
            </div>    
            <div class="clearfix">

            </div> 
            <div class="form-group col-lg-15">
                <?php $fieldName = 'restobar[' . $this->alreadyRendered . '][RdescripcionEs]'; ?>
                <label for="<?php echo $fieldName ?>">Descripción (Español)</label>
                <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big" placeholder="Descripción (Español)"></textarea>
            </div>
            <div class="clearfix">

            </div> 
            <div class="form-group col-lg-15">
                <?php $fieldName = 'restobar[' . $this->alreadyRendered . '][RdescripcionEn]'; ?>
                <label for="<?php echo $fieldName ?>">Descripción (Inglés)</label>
                <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big" placeholder="Descripción (Inglés)"></textarea>
            </div>
        </div>
    </div>
</div>