<div class="form-container">
    <blockquote>
        <?php if($this->title){?>
            <p class="text-primary"><?php echo ($this->icon) ? '<label class="glyphicon glyphicon-'.$this->icon.'"></label> ' : '' ;?> <?php echo $this->title?></p>
        <?php } ?>
        <?php if($this->description){?>
            <small><?php echo $this->description?></small>
        <?php } ?>
    </blockquote>
    <form id="newsForm" method="post" enctype="multipart/form-data" novalidate>
        <div class="form-group col-lg-15">
            <?php $fieldName = 'TNNombre';?>
            <label for="<?php echo $fieldName?>">Tipo de noticia *</label>
            <input maxlength="<?php echo $this->maxlenghtInput?>" type="text" id="<?php echo $fieldName?>" name="<?php echo $fieldName?>" class="form-control" placeholder="Título" data-validate="<?php echo $this->validations[$fieldName]?>">        
        </div>   
        
        <br>
        <div class="btn-group">
            <button type="submit" name="submit" class="btn btn-primary" data-loading-text="Validando...">Guardar</button>
            <?php /*<button type="button" data-toggle="button" class="btn btn-info" data-rel="popover" data-content="asdasdasd" title="Información">Información</button>*/?>
            <button type="button" class="btn btn-danger" onclick='location.href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'index'), '', true)?>"'>Cancelar</button>
        </div>
    </form>
</div>