<h2>Nuevo usuario registrado</h2>
<p><b>Nombre:</b> <?php echo $this->post['SNombre'];?></p>
<p><b>Email:</b> <a href="mailto:<?php echo $this->post['SEmail'];?>"><?php echo $this->post['SEmail'];?></a></p>
<p><b>Empresa:</b> <?php echo $this->post['SEmpresa'];?></p>
<p><b>Teléfono:</b> <?php echo $this->post['STelefono'];?></p>
<p><a href="<?php echo $this->serverUrl().$this->url(array('module'=>'admin','controller'=>'suscriptor','action'=>'edit','id'=>$this->id));?>">Activar cuenta</a> (Debes iniciar sesión como administrador)</p>