<div class="form-container">
    <blockquote>
        <?php if ($this->title) { ?>
            <p class="text-primary"><?php echo ($this->icon) ? '<label class="glyphicon glyphicon-' . $this->icon . '"></label> ' : ''; ?> <?php echo $this->title ?></p>
        <?php } ?>
        <?php if ($this->description) { ?>
            <small><?php echo $this->description ?></small>
        <?php } ?>
    </blockquote>
    <form id="userForm" method="post" novalidate>
        <div class="form-group col-lg-15">
            <?php $fieldName = 'SNombre'; ?>
            <label for="SNombre">Nombre *</label>
            <input value="<?php echo $this->result[$fieldName]?>" type="text" id="<?php echo $fieldName?>" name="<?php echo $fieldName?>" class="form-control" placeholder="Nombre" data-validate="required">
        </div>   
        <div class="form-group col-lg-15">
            <?php $fieldName = 'SEmail'; ?>
            <label for="SEmail">Email *</label>
            <input value="<?php echo $this->result[$fieldName]?>" type="email" id="SEmail" name="<?php echo $fieldName?>" class="form-control" placeholder="Email" data-validate="required|email">
        </div> 
        <div class="form-group col-lg-15">
            <?php $fieldName = 'SEmpresa'; ?>
            <label for="SEmpresa">Empresa </label>
            <input value="<?php echo $this->result[$fieldName]?>" type="text" id="SEmpresa" name="<?php echo $fieldName?>" class="form-control" placeholder="Empresa" >
        </div> 
        <div class="form-group col-lg-15">
            <?php $fieldName = 'STelefono'; ?>
            <label for="STelefono">Teléfono </label>
            <input value="<?php echo $this->result[$fieldName]?>" type="text" id="STelefono" name="<?php echo $fieldName?>" class="form-control" placeholder="Teléfono" >
        </div>
        <div class="form-group col-lg-15">
            <?php $fieldName = 'SPassword'; ?>
            <label for="SPassword">Contraseña *</label>
            <input value="<?php echo $this->result[$fieldName]?>" type="text" id="SPassword" name="<?php echo $fieldName?>" class="form-control" placeholder="Contraseña" data-validate="required">
        </div>
        <div class="form-group col-lg-15">
            <?php $fieldName = 'SIDPerfil'; ?>
            <label for="<?php echo $fieldName ?>">Perfil</label>
            <br>
            <select class="form-control" name="<?php echo $fieldName ?>" id="<?php echo $fieldName ?>">
            <option value="">Seleccione un perfil...</option>
            <?php foreach ($this->perfiles as $tipo) { ?>
            <option value="<?= $tipo['IDPerfil'] ?>" <?php echo ($this->result['SIDPerfil'] == $tipo['IDPerfil']) ? 'selected=""' : '' ;?>><?= $tipo['PNombre'] ?></option>     
            <?php } ?>
            </select>
        </div>
        <div class="form-group col-lg-15">
            <?php $fieldName = 'SEstado'; ?>
            <label for="<?php echo $fieldName ?>">Estado</label>
            <br>
            <select class="form-control" name="<?php echo $fieldName ?>" id="<?php echo $fieldName ?>">
            <option value="">Seleccione un estado...</option>
            <option value="1" <?php echo ($this->result['SEstado'] == 1) ? 'selected=""' : '' ;?>>SÍ</option>     
            <option value="0" <?php echo ($this->result['SEstado'] == 0) ? 'selected=""' : '' ;?>>NO</option>    
            </select>
        </div>
        <div class="form-group col-lg-15">
            <?php $fieldName = 'lang'; ?>
            <label for="<?php echo $fieldName ?>">Idioma</label>
            <br>
            <select class="form-control" name="<?php echo $fieldName ?>" id="<?php echo $fieldName ?>">
            <option value="">Seleccione un idioma...</option>
            <option value="Es" <?php echo ($this->result['lang'] == "Es") ? 'selected=""' : '' ;?>>Es</option>     
            <option value="En" <?php echo ($this->result['lang'] == "En") ? 'selected=""' : '' ;?>>En</option>    
            </select>
        </div>
       <!--  
        <div class="form-group col-lg-4">
            <label for="Spermisos">Estado</label>
            <label class="glyphicon glyphicon-question-sign text-info" style="font-size: 20px;" data-rel="tooltipRight" title="Indica si el usuario está habilitado para ingresar al sitio o no"></label>
            <br>
            <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-info <?php echo ($this->result['SEstado'] == 1) ? 'active' : '' ;?>">
                    <input <?php echo ($this->result['SEstado'] == 1) ? 'checked=""' : '' ;?> type="radio" name="SEstado" value="1"> Habilitado
                </label>
                <label class="btn btn-danger <?php echo ($this->result['SEstado'] == 0) ? 'active' : '' ;?>">
                    <input <?php echo ($this->result['SEstado'] == 0) ? 'checked=""' : '' ;?> type="radio" name="SEstado" value="0"> Deshabilitado
                </label>
            </div>
        </div> -->
        <div class="clearfix">

        </div>
        <br>
        <div class="btn-group">
            <button type="submit" name="submit" class="btn btn-primary" data-loading-text="Validando...">Guardar</button>
            <?php /* <button type="button" data-toggle="button" class="btn btn-info" data-rel="popover" data-content="asdasdasd" title="Información">Información</button> */ ?>
            <button type="button" class="btn btn-danger" onclick='location.href = "<?php echo $this->url(array('module' => 'admin', 'controller' => 'suscriptor', 'action' => 'index'), '', true) ?>"'>Cancelar</button>
        </div>
    </form>
</div>