<h2>
    <blockquote>
        <?php if ($this->title) { ?>
            <p class="text-primary"><?php echo ($this->icon) ? '<label class="glyphicon glyphicon-' . $this->icon . '"></label> ' : ''; ?> <?php echo $this->title ?></p>
        <?php } ?>
        <?php if ($this->description) { ?>
            <small><?php echo $this->description ?></small>
        <?php } ?>
    </blockquote>
    <?php echo $this->h2; 
    $field = 'sel1';
    if(count($this->islas) >1){
        $field = 'sel1[]';
    }
    
    ?>
</h2>
<?php 
if($this->message){
	echo '<div class="message">'.$this->message.'</div>';
}
if($this->message_error){
    echo '<div class="message_error">'.$this->message_error.'</div>';
}
?>
<form name = "add_new" id = "add_new" method = "post" enctype="multipart/form-data">

<table class="table_forms" border="0" style="width: 100%;">
    <tr>   
        <td width="90%">
            <select name="idEventosIsla[]" id="idEventosIsla" multiple="multiple" size="10" style="width:100%; height:350px;">
                <?php foreach($this->islas as $isla){ ?>
                    <option value="<?php echo $isla['idEventoIsla']?>"><?php echo $isla['EInombreEs'] ." - ". $isla['EIdiaEs'] ." mes ". $isla['EImes']?></option>
                <?php } ?>
            </select>
        </td>
        
        <td align="center">
            <input type="button" class="btn btn-info" value="&uarr;"  onclick="arriba('idEventosIsla')" style="width:30px;"/><br />
            <input type="button" class="btn btn-info" value="&darr;"  onclick="abajo('idEventosIsla')" style="width:30px;"/>
        </td>
        
    </tr>
     
    <tr>
        <td colspan="2"><div id = "label_error" class="label_error">&nbsp;<?php echo $this->response ?></div></td>
    </tr> 
    <tr>
        <td colspan="2">
         <input type="button" class="btn btn-danger" name = "button_cancel" id = "button_cancel" onclick="location.href='<?php echo $this->url(array('controller'=>'evento', 'action'=>'index'));?>'" value="Cancelar">
        <input type="button" class="btn btn-primary" name = "button_sumbmit" id = "button_sumbmit" onclick="validate_form();" value="Aceptar">
        </td>
    </tr>
</table>
	
</form>
<script>
    var id_form='add_new';
    form=document.getElementById(id_form).elements;
    function validate_form(){
	
        for(var i=0; i<form.idEventosIsla.length; i++) {
            form.idEventosIsla.options[i].selected = true;
        }    
        
        if(form["button_sumbmit"].disabled==false){
            form["button_sumbmit"].disabled=true;
            send_form(document.getElementById(id_form),"Guardando por favor espere ... ");
        } 
    }
    
</script>