<div class="container">
    <div class="row">
        <div class="col-lg-12 shadow bg-light-blue">
            <h1 class="color-white light">
                <?php echo ($this->lang == 'Es') ? 'Contáctanos' : 'Contact us'; ?>
            </h1>
        </div>
    </div>
    <div class="clearfix" style="margin-top: 30px;">

    </div>

    <!-- Formulario y explicacion -->
    <div class="col-lg-12 col-md-12 col-sm-12" style="margin-bottom: 30px; padding: 0;">
        <div class="bg-white border-radius-8 pad-20">
            <div class="row">
                <div class="col-lg-12">
                    
                    <h3 class="color-a roboto light noMargin">
                        <?php echo ($this->lang == 'Es') ? 'Ingrese sus datos (todos son obligatorios)' : 'Input your account data (All data is mandatory)'; ?>
                    </h3>
                    
                    <br>
                    
                    <form id="new-account" name="new-account" method="post" role="form" novalidate>
                        
                        <div class="form-group">
                            <label class="color-a roboto" for="email"><?php echo ($this->lang == 'Es') ? 'Nombre' : 'Name'; ?></label>
                            <input data-validate="required" type="text" class="form-control" id="name" name="SNombre" placeholder="<?php echo ($this->lang == 'Es') ? 'Nombre' : 'Name'; ?>">
                        </div>
                        
                        <div class="form-group">
                            <label class="color-a roboto" for="email">Email</label>
                            <input data-validate="required|email" type="email" class="form-control" id="email" name="SEmail" placeholder="Email">
                        </div>
                        
                        <div class="form-group">
                            <label class="color-a roboto" for="enterprise"><?php echo ($this->lang == 'Es') ? 'Empresa' : 'Company'; ?></label>
                            <input type="text" class="form-control" id="enterprise" name="SEmpresa" placeholder="<?php echo ($this->lang == 'Es') ? 'Empresa' : 'Company'; ?>">
                        </div>
                        
                        <div class="form-group">
                            <label class="color-a roboto" for="phone"><?php echo ($this->lang == 'Es') ? 'Teléfono' : 'Phone'; ?></label>
                            <input type="phone" class="form-control" id="phone" name="STelefono" placeholder="<?php echo ($this->lang == 'Es') ? 'Teléfono' : 'Phone'; ?>">
                        </div>
                                     
                        <div class="form-group">
                            <label class="color-a roboto" for="phone"><?php echo ($this->lang == 'Es') ? 'Consulta' : 'Message'; ?></label>
                            <textarea id="query" name="SConsulta"  data-validate="required" class="form-control" style="resize: vertical;" placeholder="<?php echo ($this->lang == 'Es') ? 'Escriba su consulta...' : 'Write your message...'; ?>"></textarea>
                        </div>
                        
                        <br>
                        <div class="form-group">
                            <div class="g-recaptcha" data-validate="required" data-callback="enableBtn" data-sitekey="6Lef_rUUAAAAADHu1mZePsgR_nAFiwdBntp4vtDS"></div>
                        </div>
                        <!--KEY PROD-->
                        <!-- <div class="g-recaptcha" data-sitekey="6LfD_rUUAAAAAMZ6_VcSqeddRzKmK9mIL25yljyk"></div> -->
                        <br>
                        <div class="btn-group">
                            <button type="button" class="btn btn-danger" onclick='location.href = "<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), '', true) ?>"'><?php echo ($this->lang == 'Es') ? 'Cancelar' : 'Cancel'; ?></button>
                            <button type="submit" id="submit" name="submit" class="btn btn-primary"><?php echo ($this->lang == 'Es') ? 'Enviar' : 'Send'; ?></button>                            
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- end Formulario y explicacion -->

</div>
<div class="clearfix" style="margin-top: 30px;">

</div>
<!-- footer -->
<?php echo $this->partial("_partials/_footer.phtml") ?>
<!-- fin footer -->
<div class="clearfix" style="margin-top: 30px;">

</div>

</div>
</div>

<!-- HASTA ACA ES EL PRIMER PARALLAX -->

<!-- Bootstrap validate-->
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap.validate.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap.validate.<?php echo ($this->lang == 'es') ? 'es' : 'en'; ?>.js"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <script>
        $(document).ready(function() {
            document.getElementById("submit").disabled = true;
            //Formulario de la vista a validar
            $('#new-account').bt_validate();

            $.bt_validate.method(
                    'custom_pass_eq',
                    function(value) {
                        return ($('#password').val() === $('#password-repeat').val());
                    },
                    "Las contraseñas no son iguales"
                    );
        });
        function enableBtn(){
            document.getElementById("submit").disabled = false;
        }
    </script>
<!-- end Bootstrap validate-->
