<div class="container">
    <div class="row">
        <div class="col-lg-12 shadow bg-light-blue">
            <h1 class="color-white thin">
                <?php echo ($this->lang == 'Es') ? 'Hoteles en' : 'Hotels on' ;?> <?php echo $this->isle['ISnombre' . $this->lang]; ?>
            </h1>
        </div>
    </div>
    <div class="clearfix" style="margin-top: 30px;">

    </div>

    <!-- Collapse hotels -->
    <div class="row">
        <div class="panel-group" id="accordion">
            <div class="panel panel-primary">                
                <!-- Hotels list -->
                <?php if(count($this->hotelList) > 0 ) :?>                
                    <?php echo $this->partial("_partials/_hotelList.phtml", array(
                        'hotelList' => $this->hotelList,
                        'activeHotelId' => $this->hotel['idHotel'],
                        'lang' => $this->lang
                    ))?>
                <?php endif; ?>
                <!-- end Hotels list -->
            </div>
        </div>
    </div>
    <!-- End collapse hotels -->
</div>
<div class="clearfix" style="margin-top: 30px;">

</div>
<!-- footer -->
<?php echo $this->partial("_partials/_footer.phtml") ?>
<!-- fin footer -->
<div class="clearfix" style="margin-top: 30px;">

</div>

</div>
</div>

<!-- HASTA ACA ES EL PRIMER PARALLAX -->



<!-- Bootstrap gallery -->
<?php
echo $this->partial("_partials/gallery.phtml");
?>
<!-- end Bootstrap gallery -->

<script>
    
    //Maneja el active de los hoteles
    $(".panel-heading").click(function(e){
        if(!$(this).hasClass('active')){
            $(".panel-heading").removeClass('active');
            $(this).toggleClass('active');
        }else{
            
        }
    });
    
    //Abre gallery
    function openGallery(idHotel){
        $('#blueimp-gallery').data('useBootstrapModal', false);
        $('#blueimp-gallery').toggleClass('blueimp-gallery-controls', true);
        blueimp.Gallery($('.hiddenGallery.hotel-'+idHotel+' a'), $('#blueimp-gallery').data());
    }
    
    //Abre mapa
    function openMap(idHotel){
        //Saca la clase que oculta los modal
        $("#mapModal"+idHotel).removeClass("modalNone");
        $("#mapModal"+idHotel).modal("show");
    }
            
    var alreadyLoaded = new Array();
    
                
    //Handler de ajax para hoteles
    $("[data-hotel-id]").click(function(){
        var hotelId = $(this).attr("data-hotel-id");
        var target = $("#collapse-hotel-"+hotelId+" > .panel-body");
        if(alreadyLoaded.indexOf(hotelId) == -1){
            $.ajax({
                url : "<?php echo $this->url(array('controller' => 'index', 'action' => 'singlehotel'), '', true)?>" + "/hotel/" + hotelId,
            }).done(function(response){
                var answer = $(response);
                setTimeout(function(){
                    target.html(answer.hide().fadeIn(1500));
                }, 1250);
            });
        }
        //Este hotel fue cargado, lo agrego a los que ya fueron cargados
        alreadyLoaded.push(hotelId);
    });
    
    //Disparador de primer hotel
    $("[data-hotel-id=<?php echo $this->activeHotelId?>]").trigger("click");

</script>
