<!-- Slider Parallax -->
<?php echo $this->render('_partials/slider_parallax.phtml'); ?>
<!-- end Slider Parallax -->

<div class="clearfix" style="margin-top: 30px">

</div>

<div class="row shadow bg-white island-intro">

    <div class="col-lg-12 col-md-12 col-sm-12" style="padding-bottom: 15px;">

        <br>
        <h1 class="color-b light">
            <?php echo ($this->lang == 'Es') ? 'POLINESIA FRANCESA' : 'FRENCH POLYNESIA'; ?>
        </h1>

        <p class="color-a thin" style="margin-top: 8px;">
            <?php echo ($this->lang == 'Es') ? 'Esparcidos en el Océano Pacífico, a 
            mitad de camino entre Tokio y Santiago de Chile, se encuentran los archipiélagos que integran 
            la Polinesia Francesa (son 5 en total), los cuales están compuestos de un total de 118 islas' 
            : 'Spread amidst the Pacific Ocean, halfway between Tokyo and Santiago, are 
            the 5 archipelagoes in which French Plynesia is divided, which comprise a total of 118 islands'; ?>
        </p>
        <a data-toggle="collapse" class="hotelLink color-a" data-parent="#accordion" href="#collapseOne">
            <?php echo ($this->lang == 'Es') ? 'Leer más' : 'Read more'; ?>
        </a>
        <div class="clearfix">
        </div>
        <div id="collapseOne" class="collapse">
            <div class="panel-body">                
                <span class="hotelLink color-a">
                <?php echo ($this->lang == 'Es') ? 'La Polinesia Francesa se ubica en el centro del gran 
                Triángulo Polinésico cuyos tres vértices son Hawaii, Nueva Zelanda y la Isla de Pascua. 
                En medio del gran océano que separa América de Asia, nos encontramos con esta tierra mágica en 
                donde coexisten la magia de las antiguas tradiciones y la modernidad occidental.' 
            : "French Polynesia is located in the center of the great Polynesia Triangle, whose three vertices are Hawaii, 
            New Zealand and Easter Island. In the middle of the great ocean which separates the Americas from Asia, we can find 
            this magical land where the ancient tradition's magic coexists with western modernity"; ?>
                </span>
            </div>
        </div>
    </div>

</div>    

<div class="clearfix" style="margin-top: 30px">

</div>

<!-- Noticias -->
<div class="row shadow bg-white island-intro">

    <div class="col-lg-12 col-md-12 col-sm-12">

        <br>
        <h1 class="color-b light">
            <?php echo ($this->lang == 'Es') ? 'Últimas novedades' : 'Latest news'; ?>
        </h1>

    </div>

    <?php if (count($this->news) > 0) : ?>

        <?php foreach ($this->news as $keyNews => $newsInstance) : ?>

            <div class="col-lg-4 col-md-4 col-sm-12 text-center" style="padding-top: 20px;">  

                <a title="Leer +" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'news', 'n' => $newsInstance['IDNoticia']), '', true); ?>">
                    <h5 class="slab color-a ellypsis">                            
                        <?php echo date_format(new DateTime($newsInstance['NFecha']), 'd/m/Y'); ?> | <?php echo $newsInstance['NTitulo' . $this->lang]; ?>
                    </h5>
                </a>

                <br>

                <?php if ($newsInstance['NImagen']) : ?>
                    <a title="Leer +" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'news', 'n' => $newsInstance['IDNoticia']), '', true); ?>">
                        <div class="image galleryImage noMargin img-rounded">
                            <img src="<?php echo $this->baseUrl() ?>/imgs/preload.gif" data-src="<?php echo $this->baseUrl() ?>/images/m_<?php echo $newsInstance['NImagen'] ?>"/>
                        </div>
                    </a>
                <?php endif; ?>

                <br>

                <?php if ($newsInstance['NIntroduccion' . $this->lang]) : ?>
                    <p class="slab color-a truncate100" style="font-style: italic;">
                        <?php echo $newsInstance['NIntroduccion' . $this->lang]; ?>
                    </p>
                <?php endif; ?>

            </div>

            <?php if ($keyNews % 3 == 2) : ?>

                <div class="clearfix"></div>

            <?php endif; ?>

        <?php endforeach; ?>

    <?php endif; ?>

    <div class="row">
        <div class="col-lg-12">            
            <div class="container" style="text-align: center; padding-top: 15px;">
                <?php echo $this->paginationControl($this->news, 'Sliding', '_partials/_paginationControl.phtml', array('search' => $this->searched)); ?>
            </div>
        </div>
    </div>

</div>
<!-- Noticias -->

<div class="clearfix" style="margin-top: 30px;">

</div>

<!-- footer -->
<?php echo $this->partial("_partials/_footer.phtml") ?>
<!-- fin footer -->

<div class="clearfix" style="margin-top: 30px;">

</div>


<style>

    #home{
        background: -moz-linear-gradient(top, rgba(255,255,255,0.7) 0%, rgba(255,255,255,0) 50%) !important;
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,255,255,0.7)), color-stop(100%,rgba(255,255,255,0))) !important;
        background: -webkit-linear-gradient(top, rgba(255,255,255,0.7) 0%, rgba(255,255,255,0) 50%) !important;
        background: -o-linear-gradient(top, rgba(255,255,255,0.7) 0%,rgba(255,255,255,0) 50%) !important;
        background: -ms-linear-gradient(top, rgba(255,255,255,0.7) 0%,rgba(255,255,255,0) 50%) !important;
        background: linear-gradient(to bottom, rgba(255,255,255,0.7) 0%,rgba(255,255,255,0) 50%) !important;
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#00ffffff',GradientType=0 ) !important;
    }

</style>