<div class="form-container">
    <blockquote>
        <?php if ($this->title) { ?>
            <p class="text-primary"><?php echo ($this->icon) ? '<label class="glyphicon glyphicon-' . $this->icon . '"></label> ' : ''; ?> <?php echo $this->title ?></p>
        <?php } ?>
        <?php if ($this->description) { ?>
            <small><?php echo $this->description ?></small>
        <?php } ?>
    </blockquote>
    <form id="actividadIslaForm" method="post" enctype="multipart/form-data" novalidate>
        <div class="form-group col-lg-4">
            <?php $fieldName = 'idGrupoIsla'; ?>
            <label for="<?php echo $fieldName ?>">Grupo de Islas</label>
            <br>
            <select class="form-control loadIslas" name="<?php echo $fieldName ?>" id="<?php echo $fieldName ?>">
                <option value="">Seleccione un grupo de islas...</option>
                <?php foreach ($this->grupoIsla as $tipo) { ?>
                    <option value="<?= $tipo[$fieldName] ?>"><?= $tipo['GInombreEs'] ?></option>                                    
                <?php } ?>
            </select>
        </div>
        <div class="form-group col-lg-4">
            <?php $fieldName = 'idIsla'; ?>
            <label for="<?php echo $fieldName ?>">Isla *</label>
            <br>
            <select class="form-control" name="<?php echo $fieldName ?>" id="<?php echo $fieldName ?>" data-validate="<?php echo $this->validations[$fieldName] ?>">
                <option value="">Seleccione un grupo de islas...</option>
            </select>
        </div>
        <div class="form-group col-lg-4">
            <?php $fieldName = 'AIimagen'; ?>
            <label for="<?php echo $fieldName ?>">Imagen *</label>
            <input type="file" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Imagen" data-validate="<?php echo $this->validations[$fieldName] ?>">
            <p class="help-block">Archivos .jpg o .png solamente</p>
        </div>
        <div class="clearfix">
            
        </div>
        <div class="form-group col-lg-4">
            <?php $fieldName = 'AInombreEs'; ?>
            <label for="<?php echo $fieldName ?>">Nombre (Español)*</label>
            <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Español)" data-validate="<?php echo $this->validations[$fieldName] ?>">        
        </div>
        <div class="form-group col-lg-8">
            <?php $fieldName = 'AIduracionEs'; ?>
            <label for="<?php echo $fieldName ?>">Duración (Español)*</label>
            <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Duración (Español)">        
        </div>
        <div class="clearfix">

        </div>
        <div class="form-group col-lg-15">
            <?php $fieldName = 'AIdescripcionEs'; ?>
            <label for="<?php echo $fieldName ?>">Descripción (Español) *</label>
            <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big ckeditor" placeholder="Descripción (Español)"></textarea>
        </div>

        <div class="form-group col-lg-4">
            <?php $fieldName = 'AInombreEn'; ?>
            <label for="<?php echo $fieldName ?>">Nombre (Inglés) *</label>
            <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Inglés)" data-validate="<?php echo $this->validations[$fieldName] ?>">        
        </div>
        <div class="form-group col-lg-8">
            <?php $fieldName = 'AIduracionEs'; ?>
            <label for="<?php echo $fieldName ?>">Duración (Inglés)*</label>
            <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Duración (Inglés)">        
        </div>
        <div class="clearfix">

        </div>
        <div class="form-group col-lg-15">
            <?php $fieldName = 'AIdescripcionEn'; ?>
            <label for="<?php echo $fieldName ?>">Descripción (Inglés) *</label>
            <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big ckeditor" placeholder="Descripción (Inglés)"></textarea>
        </div>
        <br>
        <div class="btn-group">
            <button type="submit" name="submit" class="btn btn-primary" data-loading-text="Validando...">Guardar</button>
            <?php /* <button type="button" data-toggle="button" class="btn btn-info" data-rel="popover" data-content="asdasdasd" title="Información">Información</button> */ ?>
            <button type="button" class="btn btn-danger" onclick='location.href = "<?php echo $this->url(array('module' => 'admin', 'controller' => 'isla', 'action' => 'index'), '', true) ?>"'>Cancelar</button>
        </div>
    </form>
</div>