<div class="form-group col-lg-8"> 
    <blockquote>
        <p class="text-primary"><label class="glyphicon glyphicon-picture"></label> Agregar imágenes</p>
        <small>Puede agregar todas las imágenes necesarias. Solo archivos .jpg y .png</small>
    </blockquote>
</div>
<div class="form-group col-lg-4">        
    <label >Opciones</label>
    <div class="clearfix">

    </div>
    <div class="btn-group">
        <button 
            type="button" 
            class="btn btn-primary addInput"
            data-input-name="images[]"
            data-input-type="file"
            data-input-target="imageDiv"
            data-input-label="Imagen"
            data-input-rendered="<?php echo $this->alreadyRendered?>"
            >Agregar otra imagen</button>
    </div>
</div>
<div class="clearfix">

</div>
<div class="form-group col-lg-4">
    <?php $fieldName = 'images[]'; ?>
    <label for="<?php echo $fieldName ?>">Imagen</label>
    <div class="input-group">
        <span class="input-group-addon"><label class="glyphicon glyphicon-picture"></label></span>
        <input type="file" name="<?php echo $fieldName ?>" class="form-control" data-validate="valid_image_file">
    </div>
</div>
<div class="form-group col-lg-4">
    <?php $fieldName = 'images[]'; ?>
    <label for="<?php echo $fieldName ?>">Imagen</label>
    <div class="input-group">
        <span class="input-group-addon"><label class="glyphicon glyphicon-picture"></label></span>
        <input type="file" name="<?php echo $fieldName ?>" class="form-control" data-validate="valid_image_file">
    </div>
</div>
<div class="form-group col-lg-4">
    <label for="<?php echo $fieldName ?>">Imagen</label>
    <div class="input-group">
        <span class="input-group-addon"><label class="glyphicon glyphicon-picture"></label></span>
        <input type="file" name="<?php echo $fieldName ?>" class="form-control" data-validate="valid_image_file">
    </div>
</div>
