<div class="form-group col-lg-8"> 
    <blockquote>
        <p class="text-primary"><label class="glyphicon glyphicon-cutlery"></label> Agregar bares y restaurants</p>
        <small>Puede agregar todos los restaurants y bares necesarios. Solo el nombre es obligatorio</small>
    </blockquote>
</div>
<div class="form-group col-lg-4">        
    <label >Opciones</label>
    <div class="clearfix">

    </div>
    <div class="btn-group">
        <button 
            type="button" 
            class="btn btn-primary addAjax"
            data-input-target="restobarDiv"
            data-input-action="restobar"
            data-input-label="restobar"
            >Agregar restobar</button>
    </div>
</div>
<div class="clearfix">

</div> 
<div id="restobarDiv">
    <?php /*
    <div class="form-group col-lg-4">
        <div class="panel panel-primary">
            <div class="panel-heading">Restaurant/Bar 1</div>
            <div class="panel-body">        
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'restobar[0][RnombreEs]'; ?>
                    <label for="<?php echo $fieldName ?>">Nombre (Español)*</label>
                    <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Español)" data-validate="required">        
                </div>
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'restobar[0][RnombreEn]'; ?>
                    <label for="<?php echo $fieldName ?>">Nombre (Inglés)*</label>
                    <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Inglés)" data-validate="required">        
                </div>    
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'restobar[0][RdescripcionEs]'; ?>
                    <label for="<?php echo $fieldName ?>">Descripción (Español)</label>
                    <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big" placeholder="Descripción (Español)"></textarea>
                </div>
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'restobar[0][RdescripcionEn]'; ?>
                    <label for="<?php echo $fieldName ?>">Descripción (Inglés)</label>
                    <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big" placeholder="Descripción (Inglés)"></textarea>
                </div>
            </div>
        </div>
    </div>
     */ ?>
</div>
