<div class="menu_2">
       <a href="<?php echo $this->url(array('module'=>'admin','controller'=>'suscriptor', 'action'=>'index'),'',true);?>">Parametros de conexión</a>
       <div class="clear"></div>
</div>
<?php
    if($this->controller=='parameter'){
        ?>
        <ul> 
            <li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'parameter', 'action'=>'edit'),'',true);?>" <? echo ($this->action=='index' && $this->controller=='suscriptor')?'style="font-weight: bold;"':'';?>>Modificar</a></li>
        </ul>
        <?    
    }
 
?>
