<div class="modal fade bs-modal-lg modalNone" id="mapModal<?php echo $this->hotelId; ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <div class="row">
                    <div class="col-lg-11 logo text-center">
                        <img src="<?php echo $this->baseUrl()?>/imgs/logo.png"/>                                
                    </div>
                    <div class="col-lg-1 text-center pull-right imgsModal">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            <img src="<?php echo $this->baseUrl()?>/imgs/modal-x.png"/>
                        </button>
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <span class='zoom ex3' id='' style="cursor: zoom-in;">
                    <img class='map' src='<?php echo $this->baseUrl()?>/images/<?php echo $this->map?>' alt='Mapa'/>
                </span>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-lg-12 text-center light text-muted">
                        <br>
                        <small>Paradise Tours Tahiti · Spirit of Polynesia ® 2014</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src='<?php echo $this->baseUrl()?>/js/jquery.zoom.js'></script>
<script>
    $(document).ready(function(){
        $('#ex1').zoom();
        $('#ex2').zoom({ on:'grab' });
        $('.ex3').zoom({ on:'click' });          
        $('#ex4').zoom({ on:'toggle' });
    });
</script>
