<div class="warning">
    <div class="container">
        <div class="jumbotron">
            <h1>Antes de ver la muestra!</h1>
            <p>
                Tener en cuenta que las imágenes y los textos son <strong class="text-danger">simples muestras</strong>, 
                <strong>no es la información final del sitio</strong>. Todo lo que va a ver a continuación, es informacion "fantasía" solo con objetivos ilustrativos para tomar nota de 
                espacios, tamaños, colores y estructuras ejemplificando como quedaría el sitio con la información final cargada.
            </p>
            <p>
                <strong class="text-success">Tomar nota de</strong>: Colores, fuentes, formas y efectos (identicos a la maqueta, solo con cambios aprobados por los diseñadores).
                Esta muestra fue construida respetando rigurosamente los diseños aprobados por ustedes. Cualquier duda, contactenos!
            </p>
            <p>
                <a class="btn btn-primary btn-lg" role="button" onclick="$('.warning').fadeOut(500);">Lo entiendo!</a>
            </p>
        </div>
    </div>
</div>