<table cellspacing="0" cellpadding="0">
    <tr>
        <td valign="top" id="diplayNode" >
            <div class="title">Archivo: <?php echo $this->parameters["id"] ?></div>
            <div id="contentNode">
                <fieldset class="save">
                    <input type="button" class="buttons" name = "button_cancel" id = "button_cancel" onclick="location.href='<?php
echo $this->url(array('module' => $this->parameters['module'], 'controller' => $this->parameters['controller'], 'action' => 'index'));
?>'" value="Volver">
                    <input type="button" class="buttons" name = "button_cancel" id = "button_cancel" onclick="location.href='<?php
                           echo $this->url(array('module' => $this->parameters['module'], 'controller' => $this->parameters['controller'], 'action' => 'add'), null, true);
?>'" value="Nuevo">
                    <input type="button" class="buttons" name = "button_cancel" id = "button_cancel" onclick="location.href='<?php
                           echo $this->url(array('module' => $this->parameters['module'], 'controller' => $this->parameters['controller'], 'action' => 'edit'));
?>'" value="Editar">
                    <input type="button" class="buttons" name = "button_cancel" id = "button_cancel" 
                           onclick="location.href='<?php
                           echo $this->url(array('module' => $this->parameters['module'], 'controller' => $this->parameters['controller'], 'action' => 'delete'));
?>'" value="Eliminar">

                </fieldset>
                <fieldset>
                    <table>
                        <tr>
                            <th>Nombre: </th>
                            <?php $field = "DNombre"; ?>
                            <td><?php echo $this->result[$field] ?></td>
                        </tr>
                        <tr>
                            <th>Descripcion: </th>
                            <?php $field = "DDescripcion"; ?>
                            <td><?php echo $this->result[$field] ?></td>
                        </tr>
                    </table>
                </fieldset>
            </div>
        </td>
    </tr>
</table>