<?php echo $this->doctype()."\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('CapicuaMS'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/img/favicon.png'))
    ->prependStylesheet($this->baseUrl() . '/css/bootstrap.min.css') 
    ->prependStylesheet($this->baseUrl() . '/css/cms.css')
    ->prependStylesheet($this->baseUrl() . '/css/plus.css')
    ->prependStylesheet($this->baseUrl() . '/css/richtextarea-bootstrap.min.css')
    ?>
    <?php echo $this->headScript()
    ->prependFile($this->baseUrl() . '/extras/ckeditor_4.6.2_full/ckeditor/ckeditor.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/richtextarea-bootstrap.min.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/bootstrap.validate.en.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/bootstrap.validate.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->baseUrl() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->baseUrl() . '/js/bootstrap.min.js', 'text/javascript')
        // ->prependFile($this->baseUrl() . '/js/popover.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/jquery.min.js', 'text/javascript')
    ; ?>
    <link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/imgs/favicon.png">
    
</head>
<body>
    <nav class="navbar navbar-inverse main-navbar navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Mostrar navegación</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" data-rel="tooltipBottom" title="Página de Inicio" href="<?php echo $this->url(array('module' => 'admin','controller'=>'index', 'action'=>'index'),'',true);?>">
                <label class="glyphicon glyphicon-cloud-upload text-info" style="font-size: 15px;"></label> <b class="text-info">CapicuaMS</b>
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">
                        <img style='-webkit-filter:grayscale(100%);' src="<?php echo $this->baseUrl()."/imgs/logo.png";?>"/>
                    </a>
                </li>
                <li>
                    <a data-rel="tooltipBottom" title="Ir a sección publíca" href="<?php echo $this->url(array('module' => 'admin','controller'=>'index', 'action'=>'index'),'',true);?>">
                        <label class="glyphicon glyphicon-home"></label>
                    </a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Modulos <b class="caret"></b></a>
                    <ul class="dropdown-menu" id="siteMenu">

                    </ul>
                </li>
            </ul>                                      
            <?php echo $this->layout()->menuLogin; ?>
        </div><!-- /.navbar-collapse -->
    </nav>
    <!-- PANEL LEVEL 2 -->
    <!-- END PANEL LEVEL 2 -->
    <div class="content">
        <div class="progress progress-striped main-progressbar active">
            <div class="progress-bar progress-bar-<?php echo $this->statusBar?>" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">

            </div>
        </div>
        <div class="container">
            <?php if (!$this->noNavbar){?>
            <nav class="navbar navbar-default" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url(array('module' => 'admin','controller' => $this->controller, 'action'=>'index'),'',true);?>">
                        <?php echo $this->currentBrand?>
                    </a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <?php if($this->currentIcon){?>
                        <li>
                            <a data-rel="tooltipBottom" title="<?php echo $this->currentBrand?>" href="<?php echo $this->url(array('module' => 'admin','controller'=>'index', 'action'=>'index'),'',true);?>">
                                <label class="<?php echo $this->currentIcon?>"></label>
                            </a>
                        </li>
                        <?php } ?> 
                        <?php if(count($this->actions) > 0){?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Acciones <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li role="presentation" class="dropdown-header">Acciones disponibles</li>
                                <?php foreach($this->actions as $action){?>
                                <?php if($action['type'] == 'link'){?>
                                <li>
                                    <a href="<?php echo $this->url(array('module' => 'admin','controller'=>$action['controller'], 'action'=>$action['action']),'',true);?>"><label class="text-primary glyphicon glyphicon-<?php echo $action['icon']?>"></label> <?php echo $action['label']?></a>
                                </li>
                                <?php }else{ ?>                                    
                                <li role="presentation" class="divider"></li>
                                <?php } ?>
                                <?php } ?>
                            </ul>
                        </li>
                        <?php } ?>
                    </ul>
                    <?php if($this->enableSearch){?>
                    <form class="navbar-form navbar-right" role="search" method="post">
                        <div class="form-group">
                            <input type="text" name="search" value="<?php echo $this->searched?>" class="form-control" placeholder="Ingrese palabras...">
                        </div>
                        <button type="submit" class="btn btn-default">Buscar</button>
                    </form>                    
                    <?php } ?>
                </div><!-- /.navbar-collapse -->
            </nav>
            <?php } ?>
            
            <?php echo $this->layout()->content; ?>
        </div>            

        <?php /*<h1><?php echo $this->layout()->titleMenu; ?></h1> */ ?>
        <?php // echo $this->layout()->titleSubMenu; ?>

    </div>
    <nav class="navbar navbar-default footer" role="navigation">     
        <ul class="nav navbar-nav pull-left">
            <li>
                <p class="navbar-text text-info"><label class="glyphicon glyphicon-cloud-upload text-info"></label> <b class="text-info">CapicuaMS</b> - Administración de contenidos</p>
            </li>
        </ul>
        <ul class="nav navbar-nav pull-right">
            <li>
                <p class="navbar-text text-info"><b>Capicua Web Development</b> &COPY; <?php echo date('Y')?></p>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->baseUrl()."/imgs/logoCapicua.png";?>"/>
                </a>
            </li>                
        </ul>     
    </nav>
</body>

<script>
    $(document).ready(function() {
        var baseUrl = "<?php echo $this->baseUrl()?>";



            //Activacion de tooltips, popovers y textos de carga en botones
            $("[data-rel=tooltipTop]").tooltip({placement: 'top', delay: { show: 500, hide: 100 }});
            $("[data-rel=tooltipRight]").tooltip({placement: 'right', delay: { show: 500, hide: 100 }});
            $("[data-rel=tooltipLeft]").tooltip({placement: 'left', delay: { show: 500, hide: 100 }});
            $("[data-rel=tooltipBottom]").tooltip({placement: 'bottom', delay: { show: 500, hide: 100 }});
            $("[data-rel=popoverTop]").popover({title: 'Información', placement: 'top', delay: { show: 100, hide: 100 }, html:true});
            $("[data-rel=popoverRight]").popover({title: 'Información', placement: 'right', delay: { show: 100, hide: 100 }, html:true});
            $("[data-rel=popoverLeft]").popover({title: 'Información', placement: 'left', delay: { show: 100, hide: 100 }, html:true});
            $("[data-rel=popoverBottom]").popover({title: 'Información', placement: 'bottom', delay: { show: 100, hide: 100 }, html:true});
            $("[data-loading-text]").click(function(){
                var btn = $(this);
                btn.button('loading');
                setTimeout(function () {
                    btn.button('reset');
                }, 2000);
            });
            
            //Formulario de la vista a validar
            $('#<?php echo $this->formId?>').bt_validate();
            
            $.bt_validate.method(
              'custom_pass_eq', 
              function(value) {
                return ($('#UPassword').val() === $('#password2').val());
            },
            "Las contraseñas no son iguales"
            );                      

            $(".hideTooltip").click(
                function(){
                    $(".tooltip").slideUp(300);
                }
                );

            //Convertir textareas en editables
            //$(".rta").rta('bold italic, align-left align-center align-right, link');
           CKEDITOR.config.height = 350;
        CKEDITOR.config.width = 'auto';
        CKEDITOR.config.language = 'es';
        CKEDITOR.config.allowedContent = true;
        CKEDITOR.config.toolbar = 'MyToolbar';
        CKEDITOR.config.toolbar_MyToolbar = 
        [
        { name: 'clipboard', items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
        { name: 'editing', items: [ 'Scayt' ] },
        { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
        { name: 'insert', items: [ 'Image', 'Table', 'HorizontalRule', 'SpecialChar' ] },
        { name: 'tools', items: [ 'Maximize' ] },
        { name: 'document', items: [ 'Source' ] },
        '/',
        { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
        { name: 'paragraph', items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote' ] },
        { name: 'styles', items: [ 'Styles', 'Format' ] },
        { name: 'about', items: [ 'About' ] }
    ];;
        var initCkeditor = ( function() {
            var wysiwygareaAvailable = isWysiwygareaAvailable(),
            isBBCodeBuiltIn = !!CKEDITOR.plugins.get( 'bbcode' );

            return function() {
                // var editorElement = CKEDITOR.document.getElementsByClassName( 'rta' );
                // if ( isBBCodeBuiltIn ) {
                //     editorElement.setHtml(
                //         'Hello world!\n\n' +
                //         'I\'m an instance of [url=http://ckeditor.com]CKEditor[/url].'
                //         );
                // }
                // if ( wysiwygareaAvailable ) {
                //     CKEDITOR.replace( 'editor' );
                // } else {
                //     editorElement.setAttribute( 'contenteditable', 'true' );
                //     CKEDITOR.inline( 'editor' );
                // }
            };
            function isWysiwygareaAvailable() {
                if ( CKEDITOR.revision == ( '%RE' + 'V%' ) ) {
                    return true;
                }

                return !!CKEDITOR.plugins.get( 'wysiwygarea' );
            }
        } )();
        initCkeditor();

            //Cargar menú en layout
            $("#siteMenu").load("<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'menu'),'',true)?>");
            
            //Botones para agregar inputs
            $(".addInput").click(function(){
                var inputLabel = $(this).attr('data-input-label');
                var inputName = $(this).attr('data-input-name');
                var inputType = $(this).attr('data-input-type');
                var targetId = $(this).attr('data-input-target');
                var rendered = $(this).attr('data-input-rendered');
                $.post(
                    "<?php echo $this->url(array('module' => 'admin', 'controller' => 'ajax', 'action' => 'input'))?>/inputName/" + inputName + "/inputType/" + inputType + "/inputLabel/" + inputLabel + "/inputRendered/" + rendered,
                    function(response){
                        var input = $(response);
                        $("#" + targetId).append(input.hide().fadeIn());
                    }
                    ).always(function() {
                        $('#<?php echo $this->formId?>').bt_validate();
                    })
                    .fail(function() {
                        alert("Ocurrio algun error al intentar agregar otra imagen");
                    });
                });
            
            //Botones para seleccionar imagenes a eliminar
            $('label[data-content="Esta imagen se eliminará"]').click(function(){
                var targetImg = $(this).attr('data-target-image');
                $("#" + targetImg).toggleClass('blackAndWhite');
            });
            
            //Botones para seleccionar clubes a eliminar
            $('label[data-content="Este club se eliminará"]').click(function(){
                var targetImg = $(this).attr('data-target');
                $("#" + targetImg).toggleClass('panel-danger');
            });
            //Botones para seleccionar actividades a eliminar
            $('label[data-content="Esta actividad se eliminará"]').click(function(){
                var targetImg = $(this).attr('data-target');
                $("#" + targetImg).toggleClass('panel-danger');
            });
            //Botones para seleccionar eventos a eliminar
            $('label[data-content="Este evento se eliminará"]').click(function(){
                var targetImg = $(this).attr('data-target');
                $("#" + targetImg).toggleClass('panel-danger');
            });
            //Botones para seleccionar restobares a eliminar
            $('label[data-content="Este restobar se eliminará"]').click(function(){
                var targetImg = $(this).attr('data-target');
                $("#" + targetImg).toggleClass('panel-danger');
            });
            //Botones para seleccionar habitaciones a eliminar
            $('label[data-content="Esta habitación se eliminará"]').click(function(){
                var targetImg = $(this).attr('data-target');
                $("#" + targetImg).toggleClass('panel-danger');
            });
            //Botones para seleccionar comodidades del hotel a eliminar
            $('label[data-content="Comodidad del Hotel: Se eliminará"]').click(function(){
                var targetImg = $(this).attr('data-target');
                $("#" + targetImg).toggleClass('panel-danger');
            });
            //Botones para seleccionar comodidades de habitacion a eliminar
            $('label[data-content="Comodidad de la habitación: Se eliminará"]').click(function(){
                var targetImg = $(this).attr('data-target');
                $("#" + targetImg).toggleClass('panel-danger');
            });
            
            //Ajax para agregar islas al select de islas dependiendo el grupo de islas seleccionado
            $(".loadIslas").change(function(){
                var targetId = 'idIsla';
                var idGrupoIsla = $(this).val();
                var idIslaActual = $(this).attr('data-actual-id');
                $.post(
                    "<?php echo $this->url(array('module' => 'admin', 'controller' => 'ajax', 'action' => 'islas'))?>/idGrupoIsla/" + idGrupoIsla + "/idIslaActual/" + idIslaActual,
                    function(response){
                        var islas = $(response);
                        $("#" + targetId).html(islas.hide().fadeIn());
                    }
                    ).always(function() {
                        $('#<?php echo $this->formId?>').bt_validate();
                    })
                    .fail(function() {
                        alert("Ocurrio algun error al intentar buscar las islas");
                    });
                });
            
            //Ajax para agregar cualquier cosa por ajax desde ajaxController
            $(".addAjax").click(function(){
                var targetId = $(this).attr('data-input-target');
                var action = $(this).attr('data-input-action');
                var label = $(this).attr('data-input-label');
                //var rendered = $(this).attr('data-input-rendered');
                $.post(
                    "<?php echo $this->url(array('module' => 'admin', 'controller' => 'ajax'), '', true)?>/"+action,
                    function(response){
                        var input = $(response);
                        $("#" + targetId).append(input.hide().fadeIn());
                    }
                    ).always(function() {
                        $('#<?php echo $this->formId?>').bt_validate();    

                    //Cerrar cualquier area con un id
                    $(".closeId").click(function(){
                        var targetId = $(this).attr('data-target');
                        $("#" + targetId).fadeOut(500, function(){
                            $("#" + targetId).remove();
                        });
                    });
                })
                    .fail(function() {
                        alert("Ocurrio algun error al intentar agregar " + label);
                    });

                });

        });
    </script>  
    </html>
