<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
   
    <style>
    *{
        font-family: Verdana, Geneva, sans-serif;
    }
    </style>
</head>
<body>
    <?php echo $this->layout()->content; ?>
    <br>
    <footer>
        
    </footer>
</body>
</html>