<option value="">Seleccione un día de semana...</option>
<option <?php echo ($this->diaSeleccionado == 'Todos los días') ? 'selected=""' : '' ;?> value="Todos los días">Todos los días</option>
<option <?php echo ($this->diaSeleccionado == 'Domingo') ? 'selected=""' : '' ;?> value="Domingo">Domingo</option>
<option <?php echo ($this->diaSeleccionado == 'Lunes') ? 'selected=""' : '' ;?> value="Lunes">Lunes</option>
<option <?php echo ($this->diaSeleccionado == 'Martes') ? 'selected=""' : '' ;?> value="Martes">Martes</option>
<option <?php echo ($this->diaSeleccionado == 'Miercoles') ? 'selected=""' : '' ;?> value="Miercoles">Miercoles</option>
<option <?php echo ($this->diaSeleccionado == 'Jueves') ? 'selected=""' : '' ;?> value="Jueves">Jueves</option>
<option <?php echo ($this->diaSeleccionado == 'Viernes') ? 'selected=""' : '' ;?> value="Viernes">Viernes</option>
<option <?php echo ($this->diaSeleccionado == 'Sabado') ? 'selected=""' : '' ;?> value="Sabado">Sabado</option>