<option value="">Seleccione un mes...</option>
<option <?php echo ($this->mesSeleccionado == '1') ? 'selected=""' : '' ;?> value="1">Enero</option>
<option <?php echo ($this->mesSeleccionado == '2') ? 'selected=""' : '' ;?> value="2">Febrero</option>
<option <?php echo ($this->mesSeleccionado == '3') ? 'selected=""' : '' ;?> value="3">Marzo</option>
<option <?php echo ($this->mesSeleccionado == '4') ? 'selected=""' : '' ;?> value="4">Abril</option>
<option <?php echo ($this->mesSeleccionado == '5') ? 'selected=""' : '' ;?> value="5">Mayo</option>
<option <?php echo ($this->mesSeleccionado == '6') ? 'selected=""' : '' ;?> value="6">Junio</option>
<option <?php echo ($this->mesSeleccionado == '7') ? 'selected=""' : '' ;?> value="7">Julio</option>
<option <?php echo ($this->mesSeleccionado == '8') ? 'selected=""' : '' ;?> value="8">Agosto</option>
<option <?php echo ($this->mesSeleccionado == '9') ? 'selected=""' : '' ;?> value="9">Septiembre</option>
<option <?php echo ($this->mesSeleccionado == '10') ? 'selected=""' : '' ;?> value="10">Octubre</option>
<option <?php echo ($this->mesSeleccionado == '11') ? 'selected=""' : '' ;?> value="11">Noviembre</option>
<option <?php echo ($this->mesSeleccionado == '12') ? 'selected=""' : '' ;?> value="12">Diciembre</option>