<div class="form-group col-lg-8"> 
    <blockquote>
        <p class="text-primary"><label class="glyphicon glyphicon-font"></label> Agregar actividades del hotel</p>
        <small>Puede agregar todas las actividades necesarias. Solo el nombre es obligatorio</small>
    </blockquote>
</div>
<div class="form-group col-lg-4">        
    <label >Opciones</label>
    <div class="clearfix">

    </div>
    <div class="btn-group">
        <button 
            type="button" 
            class="btn btn-primary addAjax"
            data-input-target="actividadDiv"
            data-input-action="actividadhotel"
            data-input-label="actividad - hotel"
            >Agregar actividad</button>
    </div>
</div>
<div class="clearfix">

</div> 
<div id="actividadDiv">
    <?php /*
    <div class="form-group col-lg-4">
        <div class="panel panel-primary">
            <div class="panel-heading">Actividad 1</div>
            <div class="panel-body">        
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'actividad[0][AHnombreEs]'; ?>
                    <label for="<?php echo $fieldName ?>">Nombre (Español)*</label>
                    <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Español)" data-validate="required">        
                </div>
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'actividad[0][AHnombreEn]'; ?>
                    <label for="<?php echo $fieldName ?>">Nombre (Inglés)*</label>
                    <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Inglés)" data-validate="required">        
                </div>    
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'actividad[0][AHdescripcionEs]'; ?>
                    <label for="<?php echo $fieldName ?>">Descripción (Español)</label>
                    <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big" placeholder="Descripción (Español)"></textarea>
                </div>
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'actividad[0][AHdescripcionEn]'; ?>
                    <label for="<?php echo $fieldName ?>">Descripción (Inglés)</label>
                    <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big" placeholder="Descripción (Inglés)"></textarea>
                </div>
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'actividad[0][esPaga]'; ?>
                    <div class="btn-group" data-toggle="buttons">
                        <label class="btn btn-primary">
                            <input data-validate="required" type="radio" name="<?php echo $fieldName ?>"> Paga
                        </label>
                        <label class="btn btn-info">
                            <input data-validate="required" type="radio" name="<?php echo $fieldName ?>"> Gratuita
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
     */ ?>
</div>
