<div class="form-group col-lg-8"> 
    <blockquote>
        <p class="text-primary"><label class="glyphicon glyphicon-sort-by-attributes"></label> Agregar clubes de buceo</p>
        <small>Puede agregar todos los clubes necesarios. Solo el nombre es obligatorio</small>
    </blockquote>
</div>
<div class="form-group col-lg-4">        
    <label >Opciones</label>
    <div class="clearfix">

    </div>
    <div class="btn-group">
        <button 
            type="button" 
            class="btn btn-primary addAjax"
            data-input-action="club"
            data-input-label="club de buceo"
            data-input-target="clubDiv"
            >Agregar otro club</button>
    </div>
</div>
<div class="clearfix">

</div> 
<div id="clubDiv">
    <div class="form-group col-lg-4">
        <div class="panel panel-primary">
            <div class="panel-heading">Club de buceo 1</div>
            <div class="panel-body">        
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'club[0][CBnombreEs]'; ?>
                    <label for="<?php echo $fieldName ?>">Nombre (Español)*</label>
                    <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Español)" data-validate="required">        
                </div>
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'club[0][CBnombreEn]'; ?>
                    <label for="<?php echo $fieldName ?>">Nombre (Inglés)*</label>
                    <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Inglés)" data-validate="required">        
                </div>    
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'club[0][CBdescripcionEs]'; ?>
                    <label for="<?php echo $fieldName ?>">Descripción (Español)</label>
                    <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big" placeholder="Descripción (Español)"></textarea>
                </div>
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'club[0][CBdescripcionEn]'; ?>
                    <label for="<?php echo $fieldName ?>">Descripción (Inglés)</label>
                    <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big" placeholder="Descripción (Inglés)"></textarea>
                </div>
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'club[0][CBlink]'; ?>
                    <label for="<?php echo $fieldName ?>">Link</label>
                    <input maxlength="<?php echo $this->maxlenghtInput ?>" type="url" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Link" data-validate="www">        
                </div>
            </div>
        </div>
    </div>
</div>
