<div class="form-group col-lg-8"> 
    <blockquote>
        <p class="text-primary"><label class="glyphicon glyphicon-calendar"></label> Agregar eventos del hotel</p>
        <small>Puede agregar todos los eventos necesarios. Nombre y día son obligatorios</small>
    </blockquote>
</div>
<div class="form-group col-lg-4">        
    <label >Opciones</label>
    <div class="clearfix">

    </div>
    <div class="btn-group">
        <button 
            type="button" 
            class="btn btn-primary addAjax"
            data-input-target="eventoDiv"
            data-input-action="eventohotel"
            data-input-label="evento - hotel"
            >Agregar evento</button>
    </div>
</div>
<div class="clearfix">

</div> 
<div id="eventoDiv">
    <?php /*
    <div class="form-group col-lg-4">
        <div class="panel panel-primary">
            <div class="panel-heading">Evento 1</div>
            <div class="panel-body">        
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'evento[0][EHnombreEs]'; ?>
                    <label for="<?php echo $fieldName ?>">Nombre (Español)*</label>
                    <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Español)" data-validate="required">        
                </div>
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'evento[0][EHnombreEn]'; ?>
                    <label for="<?php echo $fieldName ?>">Nombre (Inglés)*</label>
                    <input maxlength="<?php echo $this->maxlenghtInput ?>" type="text" id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" placeholder="Nombre (Inglés)" data-validate="required">        
                </div>    
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'evento[0][EHdescripcionEs]'; ?>
                    <label for="<?php echo $fieldName ?>">Descripción (Español)</label>
                    <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big" placeholder="Descripción (Español)"></textarea>
                </div>
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'evento[0][EHdescripcionEn]'; ?>
                    <label for="<?php echo $fieldName ?>">Descripción (Inglés)</label>
                    <textarea id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control big" placeholder="Descripción (Inglés)"></textarea>
                </div>
                <div class="clearfix">

                </div> 
                <div class="form-group col-lg-15">
                    <?php $fieldName = 'evento[0][EHdiaEs]'; ?>
                    <label for="<?php echo $fieldName ?>">Nombre (Inglés)*</label>
                    <select id="<?php echo $fieldName ?>" name="<?php echo $fieldName ?>" class="form-control" data-validate="required">                    
                        <?php echo $this->partial('_dias.phtml'); ?>
                    </select>
                </div>
            </div>
        </div>
    </div>
     */ ?>
</div>
